# Generated by Django 4.2.4 on 2023-11-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SAC', '0005_situacao_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='ativo_departamento',
            new_name='ativo_depto',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='descricao_departamento',
            new_name='nome_depto',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='info_departamento',
            new_name='observacao_depto',
        ),
    ]
